version: '3'
services:
  mysql-service:
    image: mysql
    container_name: mysql-service
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./setup/data:/docker-entrypoint-initdb.d
    env_file:
      - ./setup/data/build.conf
  redis-services:
    image: redis/redis-stack
    container_name: redis-service
    ports: 
      - 6379:6379
      - 8001:8001
    volumes:
      - redis:/data

volumes:
  redis: