version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-1:
    image: &kafka-image bitnami/kafka
    container_name: kafka-1
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list"]
      start_period: 15s
      interval: 10s
  kafka-2:
    image: bitnami/kafka
    container_name: kafka-2
    ports:
      - "9002"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
  kafka-ui:
    # Reference: https://docs.kafka-ui.provectus.io/overview/getting-started
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-service
    ports:
      - 3000:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: 'kafka-ui-local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092, kafka-2:9092
  kafka-init:
    image: *kafka-image
    depends_on:
      kafka-1:
        condition: service_healthy
    command: kafka-topics.sh --create --if-not-exists --topic book-store.password --replication-factor=3 --partitions=3 --bootstrap-server kafka-0:9092
