version: '3'
services:
  mysql-service:
    image: mysql
    container_name: mysql-service
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./setup/data:/docker-entrypoint-initdb.d
    env_file:
      - ./setup/data/build.conf